services:
  db:
    image: postgres:15-alpine
    container_name: eco-db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: eco-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user_admin:password_123@db:5432/ecommerce_db
    depends_on:
      - db
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./apps/frontend
    container_name: eco-client
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data: